apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-green
  namespace: keycloak
  labels:
    app: keycloak
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
      version: green
  template:
    metadata:
      labels:
        app: keycloak
        version: green
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.2
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_VERSION
          value: "24.0.2"
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"