apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - preview-service.yaml
  - rollout.yaml
  - analysis-template.yaml

commonLabels:
  app.kubernetes.io/name: keycloak
  app.kubernetes.io/instance: keycloak-blue-green